### ISSUE TITLE
pod install 报错哦

### ISSUE THREAD

**Issue by DexSinis** [HatsuneMikuV/SHSegmentedControlTableView#10]
pod install 报错哦
`Installing SHSegmentedControl (0.0.5)

[!] Error installing SHSegmentedControl
[!] /usr/local/bin/git clone https://github.com/HatsuneMikuV/SHSegmentedControlTableView.git /var/folders/9k/k5h9c_mx7p998x9wt5g82mk00000gn/T/d20181019-4048-dtv2s2 --template= --single-branch --depth 1 --branch 0.0.5

Cloning into '/var/folders/9k/k5h9c_mx7p998x9wt5g82mk00000gn/T/d20181019-4048-dtv2s2'...
warning: Could not find remote branch 0.0.5 to clone.
fatal: Remote branch 0.0.5 not found in upstream origin
`

**Comment by HatsuneMikuV** [comment]
@DexSinis 0.0.5版本已经被移除，请改成最新的1.2.1，谢谢
