### ISSUE TITLE
预估行高的情况下，iphoneX最后一个cell无法完全显示

### ISSUE THREAD

**Issue by czl0325** [HatsuneMikuV/SHSegmentedControlTableView#11]

**Comment by czl0325** [comment]
<img width="397" alt="image" src="https://user-images.githubusercontent.com/2100549/47973703-cf4c9980-e0e0-11e8-82c1-326f2cb8ad1e.png">

不写高度的代理，采用预估行高，cell内部用massonry布局，最后一层cell无法显示完整高度

**Comment by HatsuneMikuV** [comment]
@czl0325 建议这种高度多变的cell采用计算行高，并且缓存高度，有利于性能优化，可百度tableview的性能优化做参考

**Comment by czl0325** [comment]
但是这个bug你代码里最好也改一下

**Comment by HatsuneMikuV** [comment]
@czl0325 嗯嗯，最近忙，可能修复的比较晚，所以提供的是最快捷的解决办法，等空了，我去修复下，谢谢支持
