### ISSUE TITLE
嵌套后左右滚动的问题

### ISSUE THREAD

**Issue by mxpasser** [HatsuneMikuV/SHSegmentedControlTableView#12]
hello，首先感谢你写的这个库。
在使用的过程中有个问题想请教，就是嵌套在左右切换的类似pagecontroller中时，向左右滑动，当前的SHSegmentedControlTableView页面会下沉滚动。。。

![default](https://user-images.githubusercontent.com/3272620/48236733-8ce7cd00-e3fe-11e8-9972-0f57ddbde387.gif)

**Comment by HatsuneMikuV** [comment]
@mxpasser 感谢你的支持！
现在还没解决办法，因为是计算的手势滑动，因为不知道当前操作是左右滑动还是上下滑动，所以会都动，当停止拖拽，并且达到某个临界值执行某个操作。
看你的用法，可以在上层执行滑动后，再开启SHSegmentedControlTableView的滑动交互，不知道可行不。
