### ISSUE TITLE
didSelectRowAtIndexPath 不执行

### ISSUE THREAD

**Issue by JLLJHD** [HatsuneMikuV/SHSegmentedControlTableView#13]
didSelectRowAtIndexPath 不执行

**Comment by HatsuneMikuV** [comment]
@JLLJHD 能具体点吗？

**Comment by JLLJHD** [comment]
就是继承于  SHTableView 创建的TableView  代理已设置 - (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath；这个代理不执行 点击cell没反应，是不是手势冲突了？

**Comment by JLLJHD** [comment]
就是继承于 SHTableView 创建的TableView 代理已设置 - (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath；这个代理不执行 点击cell没反应，是不是手势冲突了？ @HatsuneMikuV

**Comment by HatsuneMikuV** [comment]
@JLLJHD  我这边测试是可以的，demo里继承SHTableView的TestOneTableView里面有一句，        self.allowsSelection = NO; 查看一下，是不是也复制过去了？
