### ISSUE TITLE
你好，在别人的git

### ISSUE THREAD

**Issue by kucky** [HatsuneMikuV/SHSegmentedControlTableView#19]
+ (void)load {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        [self changeOrignalSEL:@selector(sizeThatFits:) swizzleSEL:@selector(ddy_SizeThatFits:)];
        [self changeOrignalSEL:@selector(layoutSubviews) swizzleSEL:@selector(ddy_LayoutSubviews)];
    });
}
+ (void)changeOrignalSEL:(SEL)orignalSEL swizzleSEL:(SEL)swizzleSEL {
    Method originalMethod = class_getInstanceMethod([self class], orignalSEL);
    Method swizzleMethod = class_getInstanceMethod([self class], swizzleSEL);
    if (class_addMethod([self class], orignalSEL, method_getImplementation(swizzleMethod), method_getTypeEncoding(swizzleMethod))) {
        class_replaceMethod([self class], swizzleSEL, method_getImplementation(originalMethod), method_getTypeEncoding(originalMethod));
    } else {
        method_exchangeImplementations(originalMethod, swizzleMethod);
    }
}
- (CGSize)ddy_SizeThatFits:(CGSize)size {
    CGSize navigationBarSize = [self ddy_SizeThatFits:size];
    if (@available(iOS 11, *)) {
        navigationBarSize.height = navigationBarSize.height + [[UIApplication sharedApplication] statusBarFrame].size.height;
    }
    return navigationBarSize;
}

- (void)ddy_LayoutSubviews {
    [self ddy_LayoutSubviews];
    if (@available(iOS 11, *)) {
        for (UIView *aView in self.subviews) {
            if ([@[@"_UINavigationBarBackground", @"_UIBarBackground"] containsObject:NSStringFromClass([aView class])]) {
                aView.frame = CGRectMake(0, -CGRectGetMinY(self.frame), CGRectGetWidth(self.frame), CGRectGetHeight(self.frame)+CGRectGetMinY(self.frame));
            }
        }
    }
    
}

**Comment by kucky** [comment]
此段代码目的是为了解决状态栏缩放导致颜色设置失效的问题，请问在你的gitHub的哪个项目上，我想学习一下。

**Comment by HatsuneMikuV** [comment]
@kucky 我的github中并没这个相关的代码，透明渐变我是改的透明度，我工作项目中使用的是自定义导航栏，可以随意更改

**Comment by HatsuneMikuV** [comment]
@kucky 你直接在github上搜索_UINavigationBarBackground   code  有很多类似的  你可以找找看
