### ISSUE TITLE
使用过程中遇到的问题

### ISSUE THREAD

**Issue by coderWeil** [HatsuneMikuV/SHSegmentedControlTableView#2]
在使用第一个demo的时候，需求是顶部top高度动态改变，我设置为计算得到的值得时候列表无法滚动，设置为一个静态值就可以滚动，这个问题您有遇到过吗

**Comment by HatsuneMikuV** [comment]
每次动态改变时，重新赋值top试试呢？

**Comment by coderWeil** [comment]
原因是我算出来的高度有好几位小数值，我对计算的结果取整，再赋值给top后就可以了，这个问题挺诡异的

**Comment by HatsuneMikuV** [comment]
@guyuliunian 对于ios的gpu渲染    最好使用的值是0.5的整数倍，以提高gpu浮点数计算的效率，有时我们的值就是不是0.5的整数倍，我选择的方式是向上取整1，比如51.3，我用ceilf(51.3) == 52.f，这样就达到提升浮点数计算的效率，而且只增加了最大可能接近1像素的可能
