### ISSUE TITLE
后台切换到前台，滑动标签后 Crash

### ISSUE THREAD

**Issue by 200895045** [HatsuneMikuV/SHSegmentedControlTableView#20]
这几个UIFont 改成strong就好了

@property (nonatomic, strong) UIFont  * _Nonnull titleNormalFont;
/** 选中字体大小 (默认15) */
@property (nonatomic, strong) UIFont  * _Nonnull titleSelectFont;
/** 小标题字体大小 */
@property (nonatomic, strong) UIFont  * _Nonnull subTitleFont;

**Comment by HatsuneMikuV** [comment]
@200895045 谢谢你的支持，这个还真没注意到，竟然用了assign，失误失误，我会尽快重新打个pod

**Comment by HatsuneMikuV** [comment]
fix --pod v1.3.3
