### ISSUE TITLE
分栏那里有办法使用自定义的View吗

### ISSUE THREAD

**Issue by peter2022Begin** [HatsuneMikuV/SHSegmentedControlTableView#21]
如题

**Comment by HatsuneMikuV** [comment]
@peterios2016 可以的，我这里面只是提供了一种类型而已，是支持自定义赋值即可，UIView类均可以
[barview--备注](https://github.com/HatsuneMikuV/SHSegmentedControlTableView/blob/master/README.md#备注)

**Comment by HatsuneMikuV** [comment]
[barview](https://github.com/HatsuneMikuV/SHSegmentedControlTableView/blob/master/README.md#备注)
