### ISSUE TITLE
SHTableView的代理方法不执行

### ISSUE THREAD

**Issue by coderWeil** [HatsuneMikuV/SHSegmentedControlTableView#4]
- (void)scrollViewDidScroll:(UIScrollView *)scrollView {
    if (self.delegateSHTableView && [self.delegateSHTableView respondsToSelector:@selector(SHTableViewScrollViewDidScroll:)]) {
        [self.delegateSHTableView SHTableViewScrollViewDidScroll:scrollView];
    }
}

**Comment by coderWeil** [comment]
今天发现个问题，我切换到某个tableView的时候，tableView不滚动，我追踪代码发现，tableView的代理方法没有执行，也就是内容的tableView滚动被外层覆盖了，这个怎么解决呢？

**Comment by HatsuneMikuV** [comment]
@guyuliunian 你的tableview是继承我的SHTableView吗？能把你的环境配置说下一下吗？或者搭个复现的demo给我，好帮助你解决问题

**Comment by coderWeil** [comment]
是继承的SHTableView，我这边的问题已经解决了，表面上是代理方法不执行的问题，实际上根本原因在于一些布局方面，我这边是两个页面公用一个tableView，两个页面中的header设置不同，我猜测是对tableView的不同操作使得偏移的时候的Y值引起了滚动的条件改变，不能达到库里面的那个临界点，这个是我自己的问题，多谢解答
