### ISSUE TITLE
头部barview 不会随着底部tableview 的滑动而自动滑动，特别是当barview 超过一屏的时候

### ISSUE THREAD

**Issue by windkisshao** [HatsuneMikuV/SHSegmentedControlTableView#5]
在SHSegmentControl.m 文件中做如下修改就实现。

原来的方法：
- (void)setSegmentSelectedIndex:(NSInteger)index  {
    if (index < self.btnArray.count) {
        [self btnClick:self.btnArray[index] isBlock:NO];
    }
}

修改过的方法：
- (void)setSegmentSelectedIndex:(NSInteger)index {
    if (index < self.btnArray.count) {
        [self btnClick:self.btnArray[index] isBlock:NO];
        
        SHTapButtonView *btn = self.btnArray[index];
        CGFloat offsetX = btn.center.x- self.bounds.size.width * 0.5;
        if (offsetX < 0) {
            offsetX = 0;
        }
        
        CGFloat maxOffsetX = self.contentSize.width - self.bounds.size.width;
        if (offsetX > maxOffsetX) {
            offsetX = maxOffsetX;
        }
        
        [self setContentOffset:CGPointMake(offsetX, 0) animated:YES];
    }
}

**Comment by HatsuneMikuV** [comment]
可以的，不过你这种情况真的是，产品有毒！！！哈哈   

我在试试有没有更好的解决方案，如果可能会在1.1.9加上你的代码，谢谢你的思路

**Comment by HatsuneMikuV** [comment]
@windkisshao 已经添加，可更新到1.1.9，谢谢你的指正
我换了一下位置，因为涉及到点击也要滑动

**Comment by windkisshao** [comment]
客气了，应该多谢你的贡献
