### ISSUE TITLE
TestOneTableView的cell的高度是不一样的iPhoneX上的底部会有偏差最下面的 cell只显示一半

### ISSUE THREAD

**Issue by yanglijunwang** [HatsuneMikuV/SHSegmentedControlTableView#7]
-(CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath{
    return arc4random()%100 + 30;
}

**Comment by HatsuneMikuV** [comment]
@yanglijunwang 已经修复这个问题   pod  更新一下即可，最新版本 是1.2.0,
