### ISSUE TITLE
导航栏透明切换这个例子中的问题

### ISSUE THREAD

**Issue by heliang219** [HatsuneMikuV/SHSegmentedControlTableView#8]
导航栏透明切换这个例子中  下面其中一个分栏滚动 为啥会影响其他分栏的位置 
操作如下： 分栏一上滑后 然后横向滑动到分栏二，分栏二则也上移了一些位置

**Comment by HatsuneMikuV** [comment]
你可以看一下   readme里面的结构图[实现原理](https://github.com/HatsuneMikuV/SHSegmentedControlTableView/blob/master/README.md#实现的原理)。
容器是tableview，内容是作为cell  切换分栏 ，其实切换的事内容容器collectionview的item，也就是说整个tableview的cell上滑了，那整个collectionview也会上滑，切换item是不会对tableview的cell的滑动做改变，所以item1上滑了  item2、item3...都会随之而动。
@heliang219 ，不知道理解的对不对，或者你可以加一下我的QQ(479069761)，录个小视频，帮你分析一下  看看是不是别的问题。
